name: example
description: "x_flutter_core — example application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.9.2
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  x_flutter_core:
    path: ../

  x_flutter_core_models:
    git:
      url: https://github.com/fakhry-alnaffar/x-flutter-core-models.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
